### ISSUE TITLE
Is mremi_url_shorten() use data in base before call bitly api ?

### ISSUE THREAD

**Issue by TheKassaK** [mremi/UrlShortenerBundle#10]
Hello,

I choose to create my Link entity for store all link generated in my DB, and it's ok, I have for each link generated a line in my table Link.

My question is, if I call from twig from example with : {{ mremi_url_shorten('bitly', url) }} an url already generated and stored in my database, this bundle don't call bitly api another time ?

I ask this for rate limit, and for now if I have to develop a cache system.

Thanks !

**Comment by mremi** [comment]
Hi @TheKassaK ,

Yep: https://github.com/mremi/UrlShortenerBundle/blob/master/Doctrine/LinkManager.php#L106
So no need any cache system to limit the API calls.

If ok for you, I let you close the issue.
